# Generated by Django 4.2.11 on 2024-07-02 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(db_comment='问题主键', primary_key=True, serialize=False)),
                ('question_text', models.CharField(db_comment='问题', max_length=200)),
                ('pub_date', models.DateTimeField(db_comment='发布时间', verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.BigAutoField(db_comment='选项主键', primary_key=True, serialize=False)),
                ('choice_text', models.CharField(db_comment='选项', max_length=200)),
                ('votes', models.IntegerField(db_comment='投票数', default=0)),
                ('question', models.ForeignKey(db_comment='问题关联', on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
