# Generated by Django 4.2.11 on 2024-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_choice_text_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(db_comment='问题主键', primary_key=True, serialize=False),
        ),
    ]
